import React from 'react';
import { AlertTriangle, Download, MapPin, Radio, ShieldAlert, Ship, Target } from 'lucide-react';

export default function EvidenceCenter({ spill, drift, suspects, onExportEvidence, onSelectVessel }) {
  const lead = suspects?.[0];
  return <main className="flex-1 overflow-y-auto bg-command-950 p-5 md:p-8"><div className="mx-auto max-w-7xl"><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><div className="mb-2 flex items-center gap-2 text-[10px] font-mono uppercase tracking-[0.25em] text-orange-300"><ShieldAlert className="h-4 w-4" /> Evidence Center</div><h1 className="text-3xl font-bold text-white">Build the case, factor by factor.</h1><p className="mt-2 text-sm text-slate-400">A scan-friendly evidence board for the final explanation.</p></div><button onClick={onExportEvidence} className="flex items-center gap-2 rounded-lg bg-orange-600 px-4 py-2.5 text-xs font-bold text-white hover:bg-orange-500"><Download className="h-4 w-4" /> Export evidence JSON</button></div>
    <div className="grid gap-4 lg:grid-cols-[1.15fr_0.85fr]"><section className="rounded-2xl border border-command-700 bg-command-900/70 p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-mono text-sm font-bold tracking-wider text-white">FORENSIC SIGNALS</h2><span className="text-[10px] text-emerald-400">LIVE DATASET</span></div><Signal icon={<MapPin />} title="Spatial proximity" value={lead ? `${lead.min_distance_to_origin_km} km CPA` : 'Pending'} detail="Closest approach to the reconstructed origin zone" tone="cyan" /><Signal icon={<Radio />} title="AIS behavior" value={lead?.has_suspicious_gap ? `${lead.gap_duration_minutes} min blackout` : 'No blackout detected'} detail="Transmission continuity during the release window" tone="red" /><Signal icon={<AlertTriangle />} title="Kinematic anomaly" value={lead?.has_spoofing_alert ? 'Spoofing alert' : 'No alert'} detail={lead?.spoofing_description || 'Speed and position behavior screened'} tone="purple" /><Signal icon={<Target />} title="Temporal alignment" value={drift ? `${drift.release_window_midpoint.substring(11, 16)} UTC` : 'Pending'} detail="Estimated release midpoint from reverse drift" tone="orange" /></section><section className="rounded-2xl border border-orange-900/60 bg-orange-950/20 p-5"><div className="flex items-center gap-2 text-xs font-bold tracking-wider text-orange-300"><Ship className="h-4 w-4" /> ORIGIN RECONSTRUCTION</div><div className="mt-5 text-4xl font-mono font-bold text-white">{drift?.dispersion_radius_km ?? 0}<span className="ml-2 text-base text-orange-300">km spread</span></div><p className="mt-2 text-xs leading-5 text-slate-400">The probable release zone is reconstructed backward from the observed slick using wind, current, leeway, and dispersion.</p><div className="mt-5 grid grid-cols-2 gap-3 text-xs"><div><span className="block text-slate-500">Origin latitude</span><b className="font-mono text-slate-200">{drift?.origin_centroid?.lat?.toFixed(4)}</b></div><div><span className="block text-slate-500">Origin longitude</span><b className="font-mono text-slate-200">{drift?.origin_centroid?.lon?.toFixed(4)}</b></div></div></section></div>
    <section className="mt-5 rounded-2xl border border-command-700 bg-command-900/70 p-5"><div className="mb-4 flex items-center gap-2 text-xs font-bold tracking-wider text-cyan-300"><Ship className="h-4 w-4" /> RANKED CANDIDATES</div><div className="space-y-2">{(suspects || []).map(suspect => <button key={suspect.mmsi} onClick={() => onSelectVessel(suspect)} className="flex w-full items-center justify-between rounded-lg border border-command-800 bg-command-950/70 p-3 text-left hover:border-cyan-600"><span><b className="text-sm text-white">#{suspect.rank} {suspect.vessel_name}</b><span className="ml-2 text-[11px] text-slate-500">{suspect.vessel_type}</span></span><span className="font-mono text-sm font-bold text-cyan-300">{suspect.suspicion_score}%</span></button>)}</div></section>
  </div></main>;
}

function Signal({ icon, title, value, detail, tone }) { const tones = { cyan: 'text-cyan-300 border-cyan-900/60', red: 'text-red-300 border-red-900/60', purple: 'text-purple-300 border-purple-900/60', orange: 'text-orange-300 border-orange-900/60' }; return <div className={`my-2 flex items-center gap-3 rounded-xl border bg-command-950/60 p-3 ${tones[tone]}`}><span>{React.cloneElement(icon, { className: 'h-5 w-5' })}</span><span className="min-w-0 flex-1"><b className="block text-xs text-slate-200">{title}</b><span className="block truncate text-[11px] text-slate-500">{detail}</span></span><strong className="text-right text-xs">{value}</strong></div>; }
